project:
  type: website

website:
  title: "Group 6"
  navbar:
    background: "#835a9c"
    
    left:
      - href: overview.html
        text: Overview
      - href: methodology.html
        text: Methodology
      - href: results_and_analysis.html
        text: Results & Analysis
      - href: lesson.html
        text: Lesson Learnt
        
    right:
      - href: index.html
        text: Home
      - href: about.html
        text: Our Team
        
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual
