project:
  type: website

website:
  title: "Group 6"
  navbar:
    left:
      - href: overview.html
        text: Overview
      - href: methodology.html
        text: Methodology
      - href: analysis.html
        text: Results & Analysis
      - href: lesson.html
        text: Lesson Learnt
        
    right:
      - href: index.html
        text: Home
      - href: about.html
        text: Our Team

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    dark: darkly
    light: flatly
editor: visual

