---
title: "Overview"
---

## Introduction

On 10th September 2023, the worst ever flood disaster of Northern Africa in the last 130 years took place in politically-unstable Libya, caused by the collapse of Derna dam on 10th September 2023. More than a thousand deaths have been recorded, with vulnerable communities suffering from the aftermath of the disaster. Hence, it is important to explore how disasters like these could be managed in Libya. Typically, the Comprehensive Emergency Management (CEM) comprising four phases--mitigation, preparedness, response and recovery-- is used to analyse disasters (Cova, 1999).

Our project is concerned about the response and recovery efforts in Derna, Libya. Given the current infrastructure, how can rescue teams efficiently assist citizens while ensuring the city has enough quality evacuation facilities to minimise casualties in the future?

In this project, we will utilise Open Source data and satellite images to understand the flooding situation that happened in Libya, and then look into the current availability of facilities for the victims to safely evacuate to. Through analysis, we hope to provide some recommendations that would improve the flood disaster response situation in Derna, Libya. 

## Motivation

Anthropogenic climate change has increased the possibility of heavy rainfall in north-eastern Libya by 50 times. Along with poorly-built dams, Libya is particularly vulnerable to floods. This is further exacerbated by the lack of capacity to respond adequately to disasters, considering the poor socio-economic situation in Libya where the needs of citizens are largely not met. Therefore, we hope to use GIS to assist in flood response efforts in Libya to assist in humanitarian efforts and ensure the well-being of vulnerable communities in Derna, Libya.

## Objectives

In this project, we will focus on fulfilling the following objectives:

1.  Using satellite-detected images to map out and understand the flood extent in Libya with respect to emergency facilities and affected sites.

2.  Performing GIS Analysis to understand the most accessible routes for the rescue operations.

3.  Recommend suitable routes and facilities suitable for the victim\'s escape.

## Data

CRS: EPSG:2080

For base map:

-   <https://elearn.smu.edu.sg/d2l/le/content/360586/viewContent/2264710/View> (Derna_city_250m_hexagon)

For flood extent:

-   <https://data.humdata.org/dataset/flood-impact-assessment-in-derna-city-centre-east-province-libya> 

With respect to facilities: 

-   Roads (<https://data.humdata.org/dataset/lby_roads_streets>)

-   Medical Facilities (<https://data.humdata.org/dataset/hotosm_lby_health_facilities>)

-   School Facilities (<https://data.humdata.org/dataset/hotosm_lby_education_facilities>)

## Project Timeline
